protocol file
mime text/*
action launch --type=overlay $EDITOR ${FILE_PATH}

protocol file
mime application/json
action launch --type=overlay $EDITOR ${FILE_PATH}

protocol file
mime image/*
action launch --type=background xdg-open ${FILE_PATH}

protocol file
action launch --type=background xdg-open ${FILE_PATH}
